"""
x_auto.py — Phase 2 + Phase 3 in one shot: follow/like on X, then
immediately claim the reward on claimyshare.

Pipeline:
  1. Source the list of pending X actions. Two modes:
       (a) Read pending_x.json (default) — generated by a prior
           `python tasks.py` run.
       (b) Run with --discover: x_auto.py calls /api/tasks itself, posts
           every eligible task to /api/tasks/complete to find out which
           ones still need a follow/like, and uses that list directly.
           No `python tasks.py` needed beforehand.
  2. Read x_accounts.tsv (cookies per name) for the X side.
  3. For every pending row whose account has filled cookies:
       - follow -> POST /1.1/friendships/create.json screen_name=<handle>
       - like   -> POST /1.1/favorites/create.json    id=<tweet_id>
       - random 30-90s delay between actions per account (anti-bot)
  4. After each successful X action, wait --claim-delay seconds for X to
     propagate, then POST /api/tasks/complete on claimyshare to credit the
     reward. Retries on "still verifying" / "not following yet" responses.
  5. Successful entries are removed from pending_x.json (or simply not
     persisted in --discover mode). Failed entries (X action failed OR
     claim kept failing) are written/kept in pending_x.json so the next
     run can retry without re-discovering.

Use --skip-claim to run Phase 2 only (legacy behavior): do the X action but
do not call claimyshare afterwards.

Examples:
  python x_auto.py                           # full pipeline from pending_x.json
  python x_auto.py --discover                # standalone: discover + X + claim
  python x_auto.py --discover --name qolvex21
  python x_auto.py --claim-delay 25          # longer wait for X propagation
  python x_auto.py --skip-claim              # legacy Phase 2 only
  python x_auto.py --dry-run                 # preview, don't POST anything

Outputs:
  x_auto.log          human-readable log
  pending_x.json      rewritten without completed entries (or removed if empty)

Exit code:
  0 if at least one action succeeded, 3 otherwise.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import requests

from core import (
    EXIT_API_ERROR,
    EXIT_OK,
    SCRIPT_DIR,
    load_accounts,
    make_logger,
)
# Re-used helpers from tasks.py. The underscore-prefixed ones are cosmetic
# private — they're pure functions and safe to call externally. Importing
# them keeps Phase 1 (discovery) and Phase 3 (claim) classifying the API
# response identically.
from tasks import (
    _classify_response,
    complete_task,
    process_account as tasks_process_account,
)

# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------

PENDING_X_PATH = SCRIPT_DIR / "pending_x.json"
X_ACCOUNTS_PATH = SCRIPT_DIR / "x_accounts.tsv"

# ---------------------------------------------------------------------------
# X endpoints (legacy v1.1 — simpler than GraphQL, stable URL)
# ---------------------------------------------------------------------------

FOLLOW_URL = "https://x.com/i/api/1.1/friendships/create.json"
LIKE_URL = "https://x.com/i/api/1.1/favorites/create.json"

# Public bearer from x.com web bundle. Same value every browser uses.
X_WEB_BEARER = (
    "AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D"
    "1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA"
)

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# ---------------------------------------------------------------------------
# Tunables
# ---------------------------------------------------------------------------

# Delay between actions for the SAME account. Random within [min, max].
# X is sensitive to burst follow/like patterns from a single session.
# 60-180s = 1-3 minute pacing, looks human-ish; lowers ban risk markedly.
ACTION_DELAY_MIN_SEC = 60
ACTION_DELAY_MAX_SEC = 180

# Delay between accounts (smaller — different sessions, less suspicious).
# 15-30s spreads load enough that X / claimyshare don't see a uniform tick.
ACCOUNT_DELAY_MIN_SEC = 15
ACCOUNT_DELAY_MAX_SEC = 30

HTTP_TIMEOUT_SEC = 20

# --- Auto-claim (Phase 3) tunables ---
# After every successful X action we wait this long to let X propagate the
# follow/like to its backend, then POST to /api/tasks/complete on
# claimyshare. Too short -> server will still say "not following this
# account yet" and we have to retry on next run.
AUTO_CLAIM_DELAY_SEC_DEFAULT = 15
# If the first claim attempt says "still verifying" / "try again later",
# fall through this progressive backoff schedule. Each entry is the wait
# BEFORE the next attempt. The schedule is sized so the cumulative wait
# crosses the per-JWT 3 req / 60s window after retry 1, guaranteeing the
# rate-limit counter has reset by the time we re-fire:
#
#   attempt 1 (initial after claim_delay) -> may be throttled
#   wait 60s   (full window reset)
#   attempt 2 -> if still throttled,
#   wait 90s
#   attempt 3 -> last try
#
# Total worst-case: claim_delay + 60 + 90 = ~165s per task.
AUTO_CLAIM_RETRY_WAITS_SEC = (60, 90)
AUTO_CLAIM_MAX_RETRIES = len(AUTO_CLAIM_RETRY_WAITS_SEC)

# --- "Already done" fast-path ---
# When X says we already follow/like the target (code 160/158/139), the X
# state has been stable for who-knows-how-long; there's no propagation to
# wait for and no reason to throttle this account as heavily as a fresh
# action. These shorter delays kick in ONLY when an action's outcome is
# "already".
ALREADY_ACTION_DELAY_SEC = 5   # sleep between actions after an "already" hit
ALREADY_CLAIM_DELAY_SEC = 5    # claim-delay override for "already" actions

# X error codes that mean "the action is already done" — treat as success.
ALREADY_FOLLOWING_CODES = {160, 158}   # 160 = already requested, 158 = already following
ALREADY_LIKED_CODES = {139}            # 139 = already favorited

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_placeholder(value: str | None) -> bool:
    """True if the cookie field is empty or still contains REPLACE_WITH_*."""
    if not value:
        return True
    return "REPLACE_WITH" in value


def _x_headers(ct0: str, auth_token: str, referer: str) -> dict:
    """Browser-like headers for an authenticated x.com action POST."""
    return {
        "authorization": f"Bearer {X_WEB_BEARER}",
        "x-csrf-token": ct0,
        "x-twitter-auth-type": "OAuth2Session",
        "x-twitter-active-user": "yes",
        "x-twitter-client-language": "en",
        "user-agent": USER_AGENT,
        "accept": "*/*",
        "accept-language": "en-US,en;q=0.9",
        "content-type": "application/x-www-form-urlencoded",
        "origin": "https://x.com",
        "referer": referer,
        "cookie": f"auth_token={auth_token}; ct0={ct0}",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
    }


def _parse_x_error_codes(body) -> list[int]:
    """Pull X error codes out of a JSON response body. Empty list if none."""
    if not isinstance(body, dict):
        return []
    errs = body.get("errors")
    if not isinstance(errs, list):
        return []
    out: list[int] = []
    for e in errs:
        if isinstance(e, dict) and isinstance(e.get("code"), int):
            out.append(e["code"])
    return out


def _post_action(
    url: str, body_form: dict, headers: dict
) -> tuple[int, dict | None]:
    """POST a form-encoded action to X. Returns (status, parsed_body)."""
    try:
        resp = requests.post(
            url,
            data=body_form,
            headers=headers,
            timeout=HTTP_TIMEOUT_SEC,
        )
    except requests.RequestException as e:
        return 0, {"error": f"network: {e}"}
    try:
        parsed = resp.json()
    except ValueError:
        parsed = {"raw": resp.text[:300]}
    return resp.status_code, parsed


def perform_follow(
    auth_token: str, ct0: str, target_handle: str
) -> tuple[str, dict]:
    """
    Follow `target_handle` (with or without leading @).

    Returns (outcome, debug):
      outcome ∈ {"ok", "already", "invalid-target", "auth", "rate-limit",
                 "error"}
    """
    handle = target_handle.lstrip("@").strip()
    if not handle:
        return "invalid-target", {"reason": "empty handle"}

    headers = _x_headers(ct0, auth_token, referer=f"https://x.com/{handle}")
    status, body = _post_action(FOLLOW_URL, {"screen_name": handle}, headers)

    if 200 <= status < 300 and isinstance(body, dict) and body.get("id_str"):
        return "ok", {"id_str": body["id_str"], "screen_name": body.get("screen_name")}

    codes = _parse_x_error_codes(body)
    if any(c in ALREADY_FOLLOWING_CODES for c in codes):
        return "already", {"codes": codes}
    if 401 <= status <= 403 or 32 in codes or 89 in codes:
        return "auth", {"http": status, "codes": codes, "body": body}
    if status == 429 or 88 in codes:
        return "rate-limit", {"http": status, "codes": codes}
    if 50 in codes or 63 in codes:  # user not found / suspended
        return "invalid-target", {"codes": codes}
    return "error", {"http": status, "body": body}


def perform_like(auth_token: str, ct0: str, tweet_id: str) -> tuple[str, dict]:
    """
    Like tweet `tweet_id` (numeric string).

    Returns (outcome, debug) with the same outcome vocabulary as
    perform_follow().
    """
    tid = (tweet_id or "").strip()
    if not tid.isdigit():
        return "invalid-target", {"reason": f"non-numeric tweet id {tid!r}"}

    headers = _x_headers(
        ct0, auth_token, referer=f"https://x.com/i/web/status/{tid}"
    )
    status, body = _post_action(LIKE_URL, {"id": tid}, headers)

    if 200 <= status < 300 and isinstance(body, dict) and body.get("id_str"):
        return "ok", {"id_str": body["id_str"]}

    codes = _parse_x_error_codes(body)
    if any(c in ALREADY_LIKED_CODES for c in codes):
        return "already", {"codes": codes}
    if 401 <= status <= 403 or 32 in codes or 89 in codes:
        return "auth", {"http": status, "codes": codes, "body": body}
    if status == 429 or 88 in codes:
        return "rate-limit", {"http": status, "codes": codes}
    if 144 in codes:  # tweet not found
        return "invalid-target", {"codes": codes}
    return "error", {"http": status, "body": body}


# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------


def load_claimyshare_creds() -> dict[str, dict]:
    """
    Return {name: {"bearer": ..., "cookie": ...}} for accounts in config.json
    that have a filled bearer and cookie. Used by --auto-claim to call
    /api/tasks/complete after an X action succeeds.

    Never raises: returns an empty dict if config.json is missing or
    malformed (BaseException catches core.load_accounts()'s sys.exit too).
    """
    out: dict[str, dict] = {}
    try:
        accounts = load_accounts()
    except BaseException:
        return out
    for acc in accounts:
        name = acc.get("name")
        bearer = acc.get("bearer_token") or acc.get("bearer") or ""
        cookie = acc.get("cookie") or ""
        if name and bearer and cookie:
            out[name] = {"bearer": bearer, "cookie": cookie}
    return out


def try_auto_claim(
    name: str,
    task_id: int,
    bearer: str,
    cookie: str,
    initial_delay_sec: int,
    log,
) -> str:
    """
    After a successful X action, wait for X to propagate, then call
    claimyshare's /api/tasks/complete. Retries with backoff on "throttled"
    (still-verifying) responses.

    Returns the final claim outcome string:
      "ok"           -> reward credited
      "already-done" -> server says already claimed
      "need-follow"  -> server still doesn't see our follow (keep action pending)
      "need-like"    -> server still doesn't see our like  (keep action pending)
      "throttled"    -> gave up after max retries (transient rate limit)
      "service-down" -> backend's X verification is broken (~24h ETA);
                        retrying inside the same run is futile, action is
                        kept pending for the next run
      "error"        -> HTTP / network / unknown response
      "skip"         -> missing task_id, nothing to claim
    """
    if not task_id:
        log(f"[{name}] [auto-claim] no task_id on action, skipping claim.")
        return "skip"

    delay = max(1, int(initial_delay_sec))
    log(f"[{name}] [auto-claim] waiting {delay}s for X propagation, then claim task {task_id}...")
    time.sleep(delay)

    for attempt in range(1, AUTO_CLAIM_MAX_RETRIES + 2):  # +1 initial + retries
        status, body = complete_task(bearer, cookie, task_id)
        outcome = _classify_response(status, body)

        if outcome == "ok":
            msg = ""
            if isinstance(body, dict):
                msg = str(body.get("message") or "")
            log(f"[{name}] [auto-claim] [ok] task {task_id} claimed ({msg or 'reward credited'}).")
            return "ok"
        if outcome == "already-done":
            log(f"[{name}] [auto-claim] [already-done] task {task_id}.")
            return "already-done"
        if outcome in ("need-follow", "need-like"):
            # X action hasn't propagated yet. Use progressive backoff so the
            # next try falls outside the 60s rate-limit window.
            if attempt <= AUTO_CLAIM_MAX_RETRIES:
                backoff = AUTO_CLAIM_RETRY_WAITS_SEC[attempt - 1]
                log(
                    f"[{name}] [auto-claim] server says '{outcome}' on task "
                    f"{task_id}; waiting {backoff}s and retrying "
                    f"(attempt {attempt}/{AUTO_CLAIM_MAX_RETRIES})..."
                )
                time.sleep(backoff)
                continue
            log(f"[{name}] [auto-claim] gave up on task {task_id} after "
                f"{attempt} attempt(s) — server still reports '{outcome}'. "
                "Keeping action pending for next run.")
            return outcome
        if outcome == "throttled":
            server_msg = ""
            if isinstance(body, dict):
                server_msg = str(body.get("message") or body.get("error") or "")[:120]
            if attempt <= AUTO_CLAIM_MAX_RETRIES:
                backoff = AUTO_CLAIM_RETRY_WAITS_SEC[attempt - 1]
                log(
                    f"[{name}] [auto-claim] throttled (server: {server_msg!r}); "
                    f"waiting {backoff}s (attempt {attempt}/{AUTO_CLAIM_MAX_RETRIES})..."
                )
                time.sleep(backoff)
                continue
            log(
                f"[{name}] [auto-claim] throttled (server: {server_msg!r}), "
                f"giving up on task {task_id}."
            )
            return "throttled"
        if outcome == "service-down":
            # Backend says X verification is unavailable for ~24h. There is
            # no point spending retry budget on this in the same run. Action
            # stays in pending_x.json for the user to re-run later.
            server_msg = ""
            if isinstance(body, dict):
                server_msg = str(body.get("message") or body.get("error") or "")[:160]
            log(
                f"[{name}] [auto-claim] [service-down] task {task_id}: "
                f"{server_msg!r}. Backend says ~24h ETA; not retrying this "
                "run. Action kept pending — re-run `python x_auto.py` later."
            )
            return "service-down"
        # error / unknown
        log(f"[{name}] [auto-claim] [error] task {task_id}: status={status} body={body}")
        return "error"

    return "error"


def load_x_accounts() -> dict[str, dict]:
    """Return {name: {"auth_token": ..., "ct0": ...}} for filled rows."""
    if not X_ACCOUNTS_PATH.exists():
        sys.exit(f"[error] {X_ACCOUNTS_PATH} not found.")
    out: dict[str, dict] = {}
    with X_ACCOUNTS_PATH.open(encoding="utf-8-sig") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            name = (row.get("name") or "").strip()
            if not name:
                continue
            auth_token = (row.get("auth_token") or "").strip()
            ct0 = (row.get("ct0") or "").strip()
            if _is_placeholder(auth_token) or _is_placeholder(ct0):
                continue
            out[name] = {"auth_token": auth_token, "ct0": ct0}
    return out


def load_pending() -> dict:
    """Return the parsed pending_x.json or exit if missing/empty."""
    if not PENDING_X_PATH.exists():
        sys.exit(
            f"[error] {PENDING_X_PATH} not found. Run `python tasks.py` "
            "first to generate the pending list, or pass --discover to "
            "have x_auto.py build it on the fly."
        )
    try:
        data = json.loads(PENDING_X_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.exit(f"[error] {PENDING_X_PATH} not valid JSON: {e}")
    accounts = data.get("accounts") or {}
    if not accounts:
        sys.exit(
            f"[info] {PENDING_X_PATH} is empty — nothing to do. "
            "Run `python tasks.py` again or pass --discover to rebuild it."
        )
    return data


def discover_pending(
    log,
    only_name: str | None,
    dry_run: bool,
) -> tuple[dict, dict]:
    """
    Run Phase 1 inline: walk every claimyshare account, fetch its task list,
    POST /api/tasks/complete for each eligible task, and collect the
    follow/like targets that the server still wants verified.

    Returns (accounts_pending, discovery_stats):
      accounts_pending = {name: [pending_x_entry, ...]}
      discovery_stats  = aggregated counters across all accounts (ok,
                         need_follow, need_like, already_done, throttled,
                         error, skipped_other, reward_sol).

    Side effect: tasks that DON'T need an X action are claimed in this
    pass too, so the caller doesn't have to. This is the same behavior as
    `python tasks.py` — we're just calling its per-account worker directly.
    """
    try:
        accounts = load_accounts()
    except BaseException as e:  # noqa: BLE001 - core.load_accounts may sys.exit
        log(f"[discover] failed to load config.json: {e}")
        return {}, {}

    if only_name:
        accounts = [a for a in accounts if a.get("name") == only_name]
        if not accounts:
            log(f"[discover] account {only_name!r} not found in config.json.")
            return {}, {}

    log(f"[discover] scanning {len(accounts)} account(s) for pending X tasks...")

    accounts_pending: dict[str, list] = {}
    agg = {
        "ok": 0, "need_follow": 0, "need_like": 0, "already_done": 0,
        "throttled": 0, "error": 0, "skipped_other": 0, "reward_sol": 0.0,
    }

    for i, acc in enumerate(accounts):
        name = acc.get("name", "?")
        log(f"[discover] === account {i + 1}/{len(accounts)}: {name} ===")
        # tasks_process_account does fetch_tasks + per-task complete_task,
        # claims simple tasks, and returns pending_x for follow/like ones.
        result = tasks_process_account(acc, log, dry_run=dry_run)
        for k in agg:
            if k in result:
                agg[k] += result[k]
        pending = result.get("pending_x") or []
        if pending:
            accounts_pending[name] = list(pending)

    log(
        f"[discover] done | claimed_ok={agg['ok']} "
        f"need_follow={agg['need_follow']} need_like={agg['need_like']} "
        f"already_done={agg['already_done']} throttled={agg['throttled']} "
        f"error={agg['error']} reward_sol+={agg['reward_sol']:.6f}"
    )
    return accounts_pending, agg


def save_pending(remaining: dict[str, list], log) -> None:
    """Rewrite pending_x.json with only unfinished entries (or delete)."""
    if not remaining:
        if PENDING_X_PATH.exists():
            try:
                PENDING_X_PATH.unlink()
                log(f"[pending-x] removed {PENDING_X_PATH.name} (all done).")
            except OSError as e:
                log(f"[pending-x] could not remove file: {e}")
        return

    payload = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "accounts": remaining,
    }
    try:
        PENDING_X_PATH.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        total = sum(len(v) for v in remaining.values())
        log(
            f"[pending-x] {total} action(s) still pending across "
            f"{len(remaining)} account(s)."
        )
    except OSError as e:
        log(f"[pending-x] FAILED to rewrite: {e}")


# ---------------------------------------------------------------------------
# Per-account worker
# ---------------------------------------------------------------------------


def process_account(
    name: str,
    actions: list[dict],
    creds: dict,
    log,
    dry_run: bool,
    auto_claim: bool = False,
    claim_creds: dict | None = None,
    claim_delay_sec: int = AUTO_CLAIM_DELAY_SEC_DEFAULT,
) -> tuple[list[dict], dict]:
    """
    Walk one account's pending actions, executing each one.

    When auto_claim is True AND claim_creds has bearer+cookie, after each
    successful X action we additionally POST /api/tasks/complete to claim
    the reward. Actions whose claim still says "need-follow"/"need-like"
    are kept in the pending list so the next run can retry.

    Returns (still_pending_for_this_account, stats).
    """
    auth_token = creds["auth_token"]
    ct0 = creds["ct0"]

    still_pending: list[dict] = []
    stats = {"ok": 0, "already": 0, "invalid": 0, "auth": 0,
             "rate_limit": 0, "error": 0,
             "claim_ok": 0, "claim_fail": 0, "claim_skip": 0}
    last_outcome: str | None = None  # used to shorten delay after "already"

    for i, action in enumerate(actions):
        kind = action.get("action")
        target = action.get("target")
        task_id = action.get("task_id")

        if i > 0 and not dry_run:
            # Fast path: if the previous action was an already-done no-op,
            # X didn't actually change state, so we don't need to throttle
            # this account as heavily.
            if last_outcome == "already":
                sleep_s: float = ALREADY_ACTION_DELAY_SEC
                log(f"[{name}] prev action was already-done; using short "
                    f"{sleep_s:.0f}s delay before next action.")
            else:
                sleep_s = random.uniform(ACTION_DELAY_MIN_SEC, ACTION_DELAY_MAX_SEC)
                log(f"[{name}] sleeping {sleep_s:.1f}s before next action...")
            time.sleep(sleep_s)

        if dry_run:
            log(f"[{name}] [dry-run] would {kind} {target} (task {task_id})")
            still_pending.append(action)
            continue

        if kind == "follow":
            outcome, debug = perform_follow(auth_token, ct0, target)
        elif kind == "like":
            outcome, debug = perform_like(auth_token, ct0, target)
        else:
            outcome, debug = "invalid", {"reason": f"unknown action {kind!r}"}

        # Track whether the X action succeeded (real success or already-done).
        x_succeeded = outcome in ("ok", "already")

        if outcome == "ok":
            stats["ok"] += 1
            log(f"[{name}] [ok] {kind} {target} (task {task_id}) {debug}")
        elif outcome == "already":
            stats["already"] += 1
            log(f"[{name}] [already] {kind} {target} (task {task_id}) — "
                f"counting as success.")
        elif outcome == "invalid-target":
            # Target doesn't exist or tweet was deleted. Drop from pending.
            stats["invalid"] += 1
            log(f"[{name}] [invalid-target] {kind} {target} {debug} — dropping.")
        elif outcome == "auth":
            # Cookies dead for this account. Skip rest of account's actions.
            stats["auth"] += 1
            log(f"[{name}] [auth-fail] {kind} {target} {debug} — cookies "
                "expired? Keeping action for next run.")
            still_pending.append(action)
            # Skip all subsequent actions for this account — they'll all fail.
            for leftover in actions[i + 1:]:
                still_pending.append(leftover)
            break
        elif outcome == "rate-limit":
            stats["rate_limit"] += 1
            log(f"[{name}] [rate-limit] {kind} {target} {debug} — backing off "
                "from this account.")
            still_pending.append(action)
            for leftover in actions[i + 1:]:
                still_pending.append(leftover)
            break
        else:  # error / invalid-action
            stats["error"] += 1
            log(f"[{name}] [error] {kind} {target} {debug} — keeping for retry.")
            still_pending.append(action)

        # --- Optional: immediately claim the reward on claimyshare ---
        if x_succeeded and auto_claim and not dry_run:
            if not claim_creds or not claim_creds.get("bearer"):
                log(f"[{name}] [auto-claim] no claimyshare creds for this "
                    "account; skipping claim.")
                stats["claim_skip"] += 1
            else:
                # Fast path: if X already had the action before we started,
                # the state is stable — no propagation needed.
                effective_claim_delay = (
                    ALREADY_CLAIM_DELAY_SEC
                    if outcome == "already"
                    else claim_delay_sec
                )
                claim_outcome = try_auto_claim(
                    name=name,
                    task_id=task_id,
                    bearer=claim_creds["bearer"],
                    cookie=claim_creds["cookie"],
                    initial_delay_sec=effective_claim_delay,
                    log=log,
                )
                if claim_outcome in ("ok", "already-done"):
                    stats["claim_ok"] += 1
                elif claim_outcome == "skip":
                    stats["claim_skip"] += 1
                else:
                    # need-follow/need-like/throttled/service-down/error:
                    # X action was real but claim didn't stick. Put action
                    # back in pending so the next run can retry the claim
                    # (no need to redo the X side — it's already done).
                    stats["claim_fail"] += 1
                    if action not in still_pending:
                        still_pending.append(action)

        # Remember this outcome so the NEXT iteration can decide how long
        # to wait before firing its action.
        last_outcome = outcome

    return still_pending, stats


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Follow/like pending X tasks and claim the reward "
                    "on claimyshare in one shot.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python x_auto.py                              # read pending_x.json (default)\n"
            "  python x_auto.py --discover                   # standalone: discover + X + claim\n"
            "  python x_auto.py --discover --name qolvex21   # one account, full pipeline\n"
            "  python x_auto.py --claim-delay 25             # longer X propagation wait\n"
            "  python x_auto.py --skip-claim                 # legacy: do X action, don't claim\n"
            "  python x_auto.py --dry-run                    # preview only\n"
        ),
    )
    p.add_argument(
        "--name",
        help="run only this account (default: every account in the source).",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="preview actions without POSTing to X.",
    )
    p.add_argument(
        "--discover",
        action="store_true",
        help=(
            "do not read pending_x.json. Instead, walk config.json, call "
            "/api/tasks for each account, post /api/tasks/complete to find "
            "out which tasks still need an X follow/like, and act on the "
            "results in the same run. Equivalent to `tasks.py` + `x_auto.py` "
            "in one shot."
        ),
    )
    p.add_argument(
        "--skip-claim",
        action="store_true",
        help=(
            "do the X follow/like but do NOT call /api/tasks/complete "
            "afterwards. Legacy Phase-2-only mode — you'll need to run "
            "tasks.py separately to actually credit the reward."
        ),
    )
    p.add_argument(
        "--claim-delay",
        type=int,
        default=AUTO_CLAIM_DELAY_SEC_DEFAULT,
        help=(
            f"seconds to wait between X action and claim (default "
            f"{AUTO_CLAIM_DELAY_SEC_DEFAULT}). Too short = server still "
            "says 'not following yet' and we have to retry."
        ),
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    log = make_logger("x_auto.log")

    # Claim is the default; --skip-claim opts out for legacy 2-step mode.
    auto_claim = not args.skip_claim

    if args.discover:
        accounts_pending, disc_stats = discover_pending(
            log, only_name=args.name, dry_run=args.dry_run
        )
        if not accounts_pending:
            errors = int(disc_stats.get("error", 0))
            throttled = int(disc_stats.get("throttled", 0))
            if errors or throttled:
                # Distinguish "genuinely nothing pending" from "discovery
                # itself failed" so the user doesn't assume the queue is
                # empty when really we never managed to read it.
                log(
                    "[discover] discovery did NOT complete cleanly: "
                    f"errors={errors} throttled={throttled}. The pending "
                    "list could not be built. Wait for the rate-limit "
                    "window to clear (or stop monitor.py briefly) and "
                    "re-run `python x_auto.py --discover`."
                )
                return EXIT_API_ERROR
            log("[discover] all accounts checked; none have follow/like "
                "tasks pending right now. Nothing to do for the X side.")
            return EXIT_OK
    else:
        pending = load_pending()
        accounts_pending = pending.get("accounts") or {}

    x_creds = load_x_accounts()
    claim_creds_all = load_claimyshare_creds() if auto_claim else {}

    if auto_claim and not claim_creds_all:
        log("[warn] claim step requires bearer+cookie in config.json, but "
            "none of the accounts have both filled. Claims will be skipped. "
            "Run `python tasks.py` manually afterwards to credit rewards.")

    if args.name and not args.discover:
        # In --discover mode the filter was already applied during discovery.
        if args.name not in accounts_pending:
            print(
                f"[error] {args.name!r} has no pending actions in pending_x.json.",
                file=sys.stderr,
            )
            return EXIT_API_ERROR
        accounts_pending = {args.name: accounts_pending[args.name]}

    log(
        f"x_auto start | source={'discover' if args.discover else 'pending_x.json'} "
        f"accounts_pending={list(accounts_pending.keys())} "
        f"x_accounts_filled={len(x_creds)} "
        f"auto_claim={auto_claim} claim_delay={args.claim_delay}s "
        f"dry_run={args.dry_run}"
    )

    grand_stats = {"ok": 0, "already": 0, "invalid": 0, "auth": 0,
                   "rate_limit": 0, "error": 0,
                   "claim_ok": 0, "claim_fail": 0, "claim_skip": 0}
    remaining: dict[str, list] = {}

    account_names = list(accounts_pending.keys())
    for idx, name in enumerate(account_names):
        actions = accounts_pending[name]
        log(f"=== account {idx + 1}/{len(account_names)}: {name} "
            f"({len(actions)} action(s)) ===")

        creds = x_creds.get(name)
        if not creds:
            log(f"[{name}] [skip-no-cookies] no entry in x_accounts.tsv (or "
                "still placeholder). Keeping {n} action(s) for next run."
                .format(n=len(actions)))
            remaining[name] = list(actions)
            continue

        if idx > 0 and not args.dry_run:
            sleep_s = random.uniform(ACCOUNT_DELAY_MIN_SEC, ACCOUNT_DELAY_MAX_SEC)
            log(f"[{name}] sleeping {sleep_s:.1f}s before account starts...")
            time.sleep(sleep_s)

        still_pending, stats = process_account(
            name,
            actions,
            creds,
            log,
            args.dry_run,
            auto_claim=auto_claim,
            claim_creds=claim_creds_all.get(name),
            claim_delay_sec=args.claim_delay,
        )

        for k, v in stats.items():
            grand_stats[k] += v

        if still_pending:
            remaining[name] = still_pending

    # Summary
    log("=== summary ===")
    log(
        f"  X: ok={grand_stats['ok']} already={grand_stats['already']} "
        f"invalid-target={grand_stats['invalid']} auth-fail={grand_stats['auth']} "
        f"rate-limit={grand_stats['rate_limit']} error={grand_stats['error']}"
    )
    if auto_claim:
        log(
            f"  claim: ok={grand_stats['claim_ok']} "
            f"fail={grand_stats['claim_fail']} "
            f"skip={grand_stats['claim_skip']}"
        )

    # Update pending_x.json (don't touch in dry-run mode). In --discover
    # mode we still persist `remaining` so a follow-up run can resume the
    # actions that didn't stick (auth-fail, rate-limit, claim-failed) without
    # re-running discovery.
    if not args.dry_run:
        save_pending(remaining, log)
    else:
        log("[dry-run] not modifying pending_x.json.")

    succeeded = grand_stats["ok"] + grand_stats["already"]
    return EXIT_OK if succeeded > 0 else EXIT_API_ERROR


if __name__ == "__main__":
    sys.exit(main())
